colmap_dir: /home/phw/newdisk1/vpr_data/wankeli/wanke
mesh_path: /home/phw/Downloads/office-07-01_data/mesh/textured_mesh.obj
# 输出目录(rgb,poses,calibration,rgb_render,depth_render)
output_dir: data/ref